import mongoose from "mongoose"

// ─── Sub-schemas ─────────────────────────────────────────────────────────────
const SelectedModifierSchema = new mongoose.Schema(
  {
    groupId:    { type: String, required: true },
    optionId:   { type: String, required: true },
    name:       { type: String, required: true },
    priceCents: { type: Number, required: true }, // integer cents — never float
  },
  { _id: false }
)

const OrderItemSchema = new mongoose.Schema(
  {
    productId:          { type: mongoose.Schema.Types.ObjectId, ref: "Product", required: true },
    productName:        { type: String, required: true },   // snapshot
    basePriceCents:     { type: Number, required: true },   // snapshot — integer cents
    selectedModifiers:  { type: [SelectedModifierSchema], default: [] },
    quantity:           { type: Number, required: true, min: 1 },
    totalPriceCents:    { type: Number, required: true },   // (base + modifiers) * qty — integer cents
  },
  { _id: false }
)

const OrderSchema = new mongoose.Schema(
  {
    orderNumber: {
      type:     String,
      unique:   true,
      required: true,
      // e.g. "ORD-2026-00042" — generated by handler
    },

    userId: {
      type:     String,
      required: true,
      index:    true, 
    },

    status: {
      type:    String,
      enum:    ["PENDING", "PREPARING", "ON_THE_WAY", "DELIVERED", "CANCELLED"],
      default: "PENDING",
    },

    items: {
      type:     [OrderItemSchema],
      required: true,
    },

    // ── Pricing breakdown — all integer cents ────────────────────────────────
    subtotalCents:   { type: Number, required: true },
    taxCents:        { type: Number, required: true },
    serviceFeeCents: { type: Number, required: true },
    totalCents:      { type: Number, required: true },
  },
  { timestamps: true }
)

export const Order = mongoose.model("Order", OrderSchema)